export const artistNames = [
    "Radiohead",
    "The Rolling Stones",
    "Led Zeppelin",
    "Muse",
    "Foo Fighters",
    "The Black Keys",
    "Arctic Monkeys",
    "Arcade Fire",
    "Vampire Weekend",
    "Beck",
    "The Strokes",
    "The White Stripes",
    "Franz Ferdinand",
    "Soundgarden",
    "Kendrick Lamar",
    "Kanye West",
    "Oasis",
    "Gorillaz",
    "Queens of the Stone Age",
    "Childish Gambino"]